Add Dashboard charts
SaveSavvy-D/save-savvy-app pull request #10
Opened 2023-05-09 13:55 UTC by haroon-omer2000

## Description

This pull request adds dashboard charts/stats for a user's expenses and budgets.

## Tasks to accomplish

Make a responsive user dashboard.

2023-05-15 15:48 UTC, usamamunim requested changes

2023-05-15 15:48 UTC, usamamunim commented on src/components/pages/Dashboard/BudgetStackedBarChart.js
> +  );
You can create chartConfig.js file and move margin, tick etc settings there

Like this

export const chartConfig = {
  margin: { top: 5, right: 30, left: 20, bottom: 5 },
  tick: { display: 'none' },
  fill: 'gray',
};

then import and use as chartConfig.margin

2023-05-15 15:48 UTC, usamamunim commented on src/components/pages/Dashboard/DashboardCards.js
> +          <Card.Title>Rs 110,000</Card.Title>
Why is this value hardcoded here?

2023-05-15 15:48 UTC, usamamunim commented on src/components/pages/Dashboard/DashboardCards.js
> +          <Card.Title>Rs 35,000</Card.Title>
same as above

2023-05-15 15:48 UTC, usamamunim commented on src/utils/yup/schemas.js
> +    .min(3, 'Title must be of atleast 5 characters'),
```suggestion
    .min(3, 'Title must be of atleast 3 characters'),
```

2023-05-15 15:48 UTC, usamamunim commented on src/components/pages/Dashboard/ExpenseBarChart.js
> +        }}
Move them to constant as well

2023-05-15 15:48 UTC, usamamunim commented on src/utils/yup/schemas.js
>    amount: Yup.number().min(0, 'Too Short!').required('Required'),
why 'Too short' with number?

2023-05-16 11:34 UTC, haroon-omer2000 commented on src/components/pages/Dashboard/DashboardCards.js
> +          <Card.Title>Rs 110,000</Card.Title>
> Why is this value hardcoded here?

This will be replaced when the User profile is complete. Their earnings will be fetched used here. 
For now this is a placeholder.

2023-05-16 11:35 UTC, haroon-omer2000 commented on src/components/pages/Dashboard/DashboardCards.js
> +          <Card.Title>Rs 35,000</Card.Title>
> same as above

This has been changed already

2023-05-17 11:09 UTC, haseeb2001 approved these changes
:shipit:

2023-05-17 11:13 UTC, usamamunim approved these changes
LGTM

2023-05-17 11:22 UTC, merged