Profile page setup and backend integration
SaveSavvy-D/save-savvy-app pull request #11
Opened 2023-05-12 13:41 UTC by usamamunim

### Description
Authentication page styling and profile pages setup

1. Authentication pages styling
2. Profile create, update and delete pages setup
3. Backend integration of profile pages

2023-05-15 11:33 UTC, haroon-omer2000 commented on .env
Add this file in `gitignore`, also don't add this before committing so that this does not get pushed

2023-05-15 11:36 UTC, haroon-omer2000 commented on src/App.js
> +import store from './store/store';
I have moved the store and the Provider in index.js, rebase this with develop to get the updated change.

2023-05-15 11:42 UTC, haroon-omer2000 commented on src/components/pages/Profile/Profile.js
> +      )}
I think this would make it more readable

```suggestion
if (status === 'loading') {
    return <AppSpinner />;
}

if (!profile) {
    return <ProfileCreate />;
}
return (
    <div className='d-flex flex-column'>
      <ProfileHeader selection={setSelection} />
      <div className='bg-light-grey m-4'>
        {showSelected ? <ProfileInfo /> : <ProfileEdit />}
      </div>
    </div>
  );
```

2023-05-15 11:43 UTC, haroon-omer2000 commented on src/components/pages/Profile/ProfileCreate.js
> +    </div>
Theres no need of div here
```suggestion
      <ProfileForm />
```

2023-05-15 11:43 UTC, haroon-omer2000 commented on src/components/pages/Profile/ProfileEdit.js
> +    </div>
```suggestion
      <ProfileForm />
```

2023-05-15 11:44 UTC, haroon-omer2000 commented on src/components/pages/Profile/ProfileForm.js
> +                {' '}
```suggestion
```

2023-05-15 11:51 UTC, haroon-omer2000 commented on src/store/profileSlice.js
> +  status: STATUSES.IDLE,
rename `profile` to `data` for consistency and add an `errors` array to use in toasts
```suggestion
  data: null,
  status: STATUSES.IDLE,
  errors: []
```

2023-05-15 11:54 UTC, haroon-omer2000 commented on src/store/profileSlice.js
use helper functions from `reduxStateHelpers.js` (get latest develop) where applicable in `profileSlice.js` and remove console.log statements.
Also move all thunks above the slice for consistency.

2023-05-15 11:56 UTC, haroon-omer2000 commented on src/store/userSlice.js
> +  authErrors: [],
```suggestion
  errors: [],
```

2023-05-15 11:57 UTC, haroon-omer2000 commented on src/store/userSlice.js
use helper functions from `reduxStateHelpers.js` (get latest develop) where applicable in `userSlice.js` and remove console.log statements.
Also, move all thunks above the slice for consistency.

2023-05-15 12:01 UTC, haroon-omer2000 requested changes
Make sure to rebase before making new changes

2023-05-15 12:45 UTC, usamamunim commented on src/components/pages/Profile/Profile.js
> +      )}
Ternary operator is more professional way to write it. Ternary operator is designed for cases like this

2023-05-17 13:45 UTC, usamamunim commented on src/store/profileSlice.js
> +  status: STATUSES.IDLE,
I am handling it in other PR, where i am working on toasts

2023-05-17 13:58 UTC, haroon-omer2000 approved these changes

2023-05-17 14:55 UTC, merged